[package]
name = "bashreadline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object = { version = "0.27.0", features = ["elf"] }
libbpf-rs = { git = "https://github.com/libbpf/libbpf-rs", rev = "ebc55ba" }
libbpf-sys = "0.5.0-2"
libc = "0.2"
nix = "0.23"
plain = "0.2"
chrono = "0.4"
tokio = { version = "1.10", features = ["full"] }
libbpf-async = {path="../../libbpf-async"}

[build-dependencies]
libbpf-cargo = { git = "https://github.com/libbpf/libbpf-rs"}
